export const datos ={
  "contacts":[
    {
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "createdAt": 1706206628825,
        "comContact": "Lead de teléfono",
        "selecMC": "Propiedades.com",
        "email": "nellymoliba@hotmail.com",
        "name": "Nellyxyz",
        "telephon": "6142857672",
        "id": "1P3ApT9qXeIzgqs7loRu"
    },
    {
        "typeContact": "Arrendador",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "propCont": "Misiones Mto",
        "selecTP": "Local Comercial",
        "lastname": "Reyes",
        "telephon": "6142473425",
        "createdAt": 1697651101726,
        "rangeProp": "PRM",
        "name": "José Luis",
        "id": "1WJpR7VKT2rHFN9qvGnj"
    },
    {
        "telephon": "6141904471",
        "createdAt": 1708022585483,
        "contactStage": "Etapa 1",
        "rangeProp": "SGN",
        "lastname": "García",
        "typeContact": "Comprador",
        "selecMC": "Lona en Propiedad",
        "comContact": "Pago en efectivo",
        "name": "joselín",
        "id": "2BX63axjqep10akrbwt1"
    },
    {
        "lastname": "Rey",
        "telephon": "6144048110",
        "id": "3xi3mjaMHMlOvuaTKs3h",
        "createdAt": 1700584791711,
        "contactStage": "Etapa 1",
        "propCont": "Villa Rca",
        "name": "Paola",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "rangeProp": "SGN"
    },
    {
        "lastname": "barraza",
        "telephon": "6144581857",
        "selecMC": "Lona en Propiedad",
        "name": "gabriel",
        "id": "4D1eboJJUaHxkw9Mbcrh",
        "typeContact": "Arrendatario",
        "rangeProp": "PRM",
        "contactStage": "Etapa 1",
        "createdAt": 1709304781329
    },
    {
        "lastname": "Nuñez",
        "selecTP": "Casa",
        "id": "5m0WWtu4xVPjcWbMysuF",
        "numParks": "",
        "typeContact": "Comprador",
        "halfBathroom": "",
        "name": "edgar",
        "numBeds": "",
        "numBaths": "",
        "modePay": "",
        "selecMC": "Otro",
        "rangeProp": "TRC",
        "createdAt": 1708021642513,
        "contactStage": "Etapa 1",
        "locaProperty": [],
        "budget": "",
        "tagsProperty": [],
        "telephon": "6142151677"
    },
    {
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "lastname": "Ramos",
        "createdAt": 1696892021884,
        "propCont": "Residencial Universidad Rli",
        "rangeProp": "SGN",
        "telephon": "6141750839",
        "name": "Graciela",
        "selecMC": "Lona en Propiedad",
        "selecTP": "Casa",
        "id": "69zCF7NwKmq5fN0o8Pcb"
    },
    {
        "typeContact": "Comprador",
        "telephon": "6144097374",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "propCont": "Angel Trias Rpo",
        "rangeProp": "SXT",
        "createdAt": 1701113612696,
        "selecTP": "Terreno",
        "lastname": "Chavira ",
        "name": "Cesar",
        "id": "6HM3Fv5jpGvuiDXPBMhg"
    },
    {
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "createdAt": 1697469272752,
        "rangeProp": "SGN",
        "telephon": "6142509010",
        "typeContact": "Comprador",
        "name": "Esmeralda",
        "lastname": "Turcott",
        "selecMC": "Propiedades.com",
        "comContact": "Ya la habían contactado de otra inmobiliaria por la casa de Tierra y Libertad",
        "propCont": "Tierra y Libertad Mch",
        "id": "6jW15X2qfwUlD5H9DrH3"
    },
    {
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "rangeProp": "SXT",
        "selecMC": "Lona en Propiedad",
        "name": "Bladimir",
        "createdAt": 1709253788909,
        "telephon": "6251366153",
        "id": "72oj6HLM8cFCaDAuvqB9",
        "lastname": "rabadán"
    },
    {
        "lastname": "lisboa",
        "name": "Mirador y",
        "selecMC": "Lona en Propiedad",
        "telephon": "6141111031",
        "contactStage": "Etapa 1",
        "typeContact": "Arrendatario",
        "createdAt": 1721349133982,
        "id": "9EsJOd0o2i8SRXWEwLCO"
    },
    {
        "rangeProp": "PRM",
        "lastname": "Barraza",
        "contactStage": "Etapa 1",
        "name": "Gustavo",
        "createdAt": 1692743915407,
        "comContact": "Lo quiera para oficinas, actualmente tienen algo mas de 100 m2 pero ya les quedó chico",
        "selecMC": "Lona en Propiedad",
        "typeContact": "Arrendador",
        "propCont": "Misiones Mto",
        "telephon": "6141844449",
        "selecTP": "Local Comercial",
        "id": "BkHehAvWKFEqY3ucj9fn"
    },
    {
        "name": "Amauri",
        "propCont": "Residencial Universidad Rli",
        "rangeProp": "SGN",
        "comContact": "Crédito preautorizado de 2,500,000",
        "selecMC": "Lona en Propiedad",
        "createdAt": 1702426053873,
        "telephon": "6145043247",
        "lastname": "Acosta",
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "id": "C1b6YVXO3nM9t33sXmUx"
    },
    {
        "lastname": "Perez",
        "name": "Abraham",
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "comContact": "Contactó por San Felipe Vto. Jul/23",
        "propCont": "Quintas del Sol Ple",
        "id": "C83louuyCF6DrCWhMHug",
        "selecMC": "Lona en Propiedad",
        "telephon": "6142753697",
        "contactStage": "Etapa 1",
        "createdAt": 1690412372060
    },
    {
        "propCont": "Rinconada de la Sierra Eso",
        "name": "Pamela",
        "createdAt": 1688406170361,
        "telephon": "7225106087",
        "selecMC": "Lamudi",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "rangeProp": "TRC",
        "lastname": "Balderas",
        "selecTP": "Casa",
        "id": "D1o35azqOkBLyql9lK8a"
    },
    {
        "comContact": "Publicó por Facebook que vende casa, solicitando inmobiliarios",
        "telephon": "6141970553",
        "name": "Mario",
        "selecMC": "Otro",
        "createdAt": 1706201860703,
        "typeContact": "Vendedor",
        "lastname": "Vega",
        "contactStage": "Etapa 1",
        "id": "Et1Jl0XBp3IA9k2YyoXi"
    },
    {
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "selecTP": "Terreno",
        "propCont": "Quintas del Sol Rli",
        "comContact": "Contactó por Quintas del Sol Rli",
        "lastname": "Ramos",
        "typeContact": "Comprador",
        "name": "Lily",
        "telephon": "6143375263",
        "rangeProp": "TRC",
        "createdAt": 1697741943779,
        "id": "GZXgOpk4Dju4k7pBKW6W"
    },
    {
        "lastname": "Torres",
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "propCont": "San Felipe Vto",
        "name": "Teresa",
        "telephon": "6141413357",
        "createdAt": 1693065455538,
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "selecTP": "Casa",
        "id": "GidgMfjgT81v2oeVYmEG"
    },
    {
        "propCont": "San Felipe Vto",
        "rangeProp": "TRC",
        "lastname": "Martínez ",
        "telephon": "6143972385",
        "name": "David",
        "selecTP": "Casa",
        "createdAt": 1690588658299,
        "typeContact": "Inmobiliario Asociado",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "id": "I8eUOZpjSGaVw1wSXEja"
    },
    {
        "lastname": "Jiménez",
        "selecTP": "Casa",
        "id": "IQ1X2HRYfCj9TjLiequg",
        "name": "Leticia",
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "propCont": "San Felipe Vto",
        "createdAt": 1696521396419,
        "selecMC": "Lona en Propiedad",
        "telephon": "6629485064",
        "comContact": "Busca especificamente en San Felipe",
        "contactStage": "Etapa 1"
    },
    {
        "lastname": "Saenz",
        "typeContact": "Comprador",
        "name": "Irma",
        "createdAt": 1705422104360,
        "telephon": "6141722920",
        "rangeProp": "SGN",
        "propCont": "Villa Rca",
        "contactStage": "Etapa 1",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "id": "J05H8QmqQKKaJpdH9MkA"
    },
    {
        "lastname": "Montoya",
        "name": "Sofia",
        "rangeProp": "TRC",
        "propCont": "Rinconada de la Sierra Eso",
        "typeContact": "Comprador",
        "telephon": "6142868214",
        "contactStage": "Etapa 1",
        "createdAt": 1701277880240,
        "email": "chofimex@gmail.com",
        "selecTP": "Casa",
        "selecMC": "Lamudi",
        "id": "JHr1iZr0nOrUZcIXf2DD"
    },
    {
        "lastname": "loya",
        "rangeProp": "SGN",
        "name": "laura",
        "telephon": "6144262272",
        "typeContact": "Comprador",
        "selecMC": "NocNok",
        "contactStage": "Etapa 1",
        "createdAt": 1711470110335,
        "email": "lauramloyas@hotmail.com",
        "id": "K2BVK0EN5E9aI4zB7qX5"
    },
    {
        "telephon": "6141052396",
        "selecMC": "Propiedades.com",
        "comContact": "Contactó por Sta. Rita Mch1",
        "rangeProp": "TRC",
        "selecTP": "Casa",
        "typeContact": "Comprador",
        "lastname": "Rascón",
        "contactStage": "Etapa 1",
        "createdAt": 1696630768040,
        "propCont": "Sta. Rita Mch",
        "name": "Manuel",
        "id": "KhUx9GfY1ZNJB5qWKhgk"
    },
    {
        "createdAt": 1689117378924,
        "name": "Nestor",
        "rangeProp": "CRT",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "telephon": "6145221574",
        "lastname": "Ojeda",
        "typeContact": "Comprador",
        "propCont": "Panamericana Rga",
        "comContact": "El fin de semana me llama para verla el lunes",
        "id": "L35ytEp0UZg7dW05KMsc"
    },
    {
        "contactStage": "Etapa 1",
        "selecMC": "Lamudi",
        "name": "Alfonso",
        "telephon": "6141635188",
        "createdAt": 1689605650746,
        "typeContact": "Comprador",
        "selecTP": "Terreno",
        "rangeProp": "PRM",
        "lastname": "Mendoza",
        "propCont": "Labor de Terrazas",
        "id": "MNZ4FSs8Pc8mNDgTkNb6"
    },
    {
        "selecMC": "Lamudi",
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "lastname": "pérez",
        "name": "Jennifer",
        "createdAt": 1708556623590,
        "telephon": "6142808064",
        "email": "hola.jenniferperez@gmail.com",
        "rangeProp": "",
        "id": "McqVl1of6x8tnrJqoU2e"
    },
    {
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "rangeProp": "TRC",
        "telephon": "6142399538",
        "lastname": "Leal",
        "propCont": "San Felipe Dve",
        "createdAt": 1700263296990,
        "name": "Victor",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "comContact": "Contactó por San Felipe Vto",
        "id": "NV5I9f11GUAL6mmnyDnS"
    },
    {
        "rangeProp": "SGN",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "typeContact": "Comprador",
        "createdAt": 1694210109513,
        "propCont": "Villa Rca",
        "contactStage": "Etapa 1",
        "name": "Gladis",
        "telephon": "6351137308",
        "lastname": "Ramos",
        "id": "NXkt15xwIdcOCMSJjyUP"
    },
    {
        "name": "Magaly",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "lastname": "Díaz",
        "propCont": "Residencial Universidad EsoSe",
        "createdAt": 1704926804154,
        "contactStage": "Etapa 1",
        "telephon": "6143945430",
        "id": "NXm7HqmLwuyBDBhAykY4"
    },
    {
        "selecMC": "Lona en Propiedad",
        "createdAt": 1689963483989,
        "rangeProp": "TRC",
        "name": "Daniel",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "selecTP": "Terreno",
        "propCont": "Quintas del Sol Rli",
        "telephon": "6144276945",
        "lastname": "Saad",
        "id": "NiMSreM70MoxAc1riYG8"
    },
    {
        "createdAt": 1701458465044,
        "typeContact": "Comprador",
        "telephon": "6145136274",
        "comContact": "Preguntó que si puede ser habiatacional",
        "name": "Alejandra",
        "selecMC": "",
        "selecTP": "Terreno",
        "contactStage": "Etapa 1",
        "lastname": "Madrigal",
        "rangeProp": "CRT",
        "propCont": "Riveras de Sacramento Jma",
        "id": "Nqthq5NV42UpVI4JYJER"
    },
    {
        "name": "Enrique",
        "contactStage": "Etapa 1",
        "email": "ceramglez@live.com",
        "propCont": "Residencial Universidad Rli",
        "selecTP": "Casa",
        "createdAt": 1696267924619,
        "comContact": "La casa es para la hija, cotactoó por Rinconadad de la Sierra Eso. Pero quere habitarla de inmediato.",
        "telephon": "6141534856",
        "selecMC": "Otro",
        "typeContact": "Comprador",
        "lastname": "Ramírez",
        "rangeProp": "SGN",
        "id": "Ri8pQDcYEP7Bs8QGMKwB"
    },
    {
        "lastname": "Palma",
        "propCont": "Panamericana Rga",
        "telephon": "6141023036",
        "selecTP": "Casa",
        "rangeProp": "CRT",
        "typeContact": "Comprador",
        "name": "Everardo",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "createdAt": 1688778607608,
        "id": "TP53AEmqCauQWb5uD2iP"
    },
    {
        "selecMC": "Lona en Propiedad",
        "createdAt": 1706301323076,
        "lastname": "Loera",
        "propCont": "Angel Trias Rpo",
        "contactStage": "Etapa 1",
        "selecTP": "Terreno",
        "name": "Miguel",
        "typeContact": "Comprador",
        "telephon": "6142291185",
        "rangeProp": "SXT",
        "id": "TpTFj08vrZzJ2eZvs2Lv"
    },
    {
        "createdAt": 1703284956129,
        "contactStage": "Etapa 1",
        "selecTP": "Local Comercial",
        "rangeProp": "PRM",
        "telephon": "6145378779",
        "propCont": "San Felipe Mto3",
        "selecMC": "Lona en Propiedad",
        "typeContact": "Arrendatario",
        "name": "Jany",
        "id": "UrGARaaK4l9ttKvBZz67"
    },
    {
        "halfBathroom": "",
        "typeContact": "Comprador",
        "tagsProperty": [],
        "modePay": "",
        "name": "Beto",
        "lastname": "Martínez",
        "numBaths": "",
        "id": "V4AYf6GHVjeYaIgbQTwl",
        "budget": "",
        "rangeProp": "SGN",
        "createdAt": 1706662074086,
        "selecMC": "Lona en Propiedad",
        "numParks": "",
        "contactStage": "Etapa 1",
        "selecTP": "Casa",
        "locaProperty": [],
        "telephon": "6141740307",
        "numBeds": ""
    },
    {
        "modePay": "",
        "halfBathroom": "",
        "budget": "",
        "tagsProperty": [],
        "numBaths": "",
        "rangeProp": "",
        "id": "WeH6x919r9wIOaeon43j",
        "selecTP": "Terreno",
        "numParks": "",
        "telephon": "6142686888",
        "createdAt": 1708557509319,
        "selecMC": "Vivanuncios",
        "contactStage": "Etapa 1",
        "numBeds": "",
        "email": "rurangab@gmail.com",
        "typeContact": "Comprador",
        "locaProperty": [],
        "lastname": "huranga",
        "name": "Raúl"
    },
    {
        "contactStage": "Etapa 1",
        "selecMC": "Lamudi",
        "propCont": "Zona Centro",
        "typeContact": "Comprador",
        "createdAt": 1699034549480,
        "name": "Hugo",
        "email": "hlberto_devora@yahoo.com.mx",
        "selecTP": "Terreno",
        "lastname": "Dévora",
        "rangeProp": "TRC",
        "telephon": "6391123317",
        "id": "XmNWZGIyQjaY84pxwfgh"
    },
    {
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "contactStage": "Etapa 1",
        "telephon": "6141360975",
        "name": "teresa",
        "lastname": "delgado",
        "selecMC": "Propiedades.com",
        "createdAt": 1712776301294,
        "id": "XrRtSZy6Zvs5zza2tpQY"
    },
    {
        "propCont": "Misiones Mto",
        "name": "Jorge",
        "lastname": "Pérez",
        "contactStage": "Etapa 1",
        "telephon": "6143458919",
        "typeContact": "Comprador",
        "rangeProp": "PRM",
        "createdAt": 1703803111242,
        "selecMC": "Lona en Propiedad",
        "selecTP": "Local Comercial",
        "id": "Z1rdP1Y91CQ2wOBcSJua"
    },
    {
        "createdAt": 1696630408018,
        "name": "Bertha Elena",
        "contactStage": "Etapa 1",
        "telephon": "6142270150",
        "lastname": "Vazquez",
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "propCont": "Sta. Rita Mch",
        "comContact": "Contactó por Sta. Rita Mch1",
        "selecTP": "Casa",
        "selecMC": "Propiedades.com",
        "id": "ZO8VBUwQ7SdK31UwxTK7"
    },
    {
        "lastname": "López",
        "telephon": "6142071456",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "name": "Eduardo",
        "id": "aJC7TlEcWYMlKdKKMpsK",
        "propCont": "San Felipe Vto",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "rangeProp": "TRC",
        "createdAt": 1693873654231
    },
    {
        "selecTP": "Casa",
        "rangeProp": "SGN",
        "selecMC": "Lona en Propiedad",
        "propCont": "Villa Rca",
        "comContact": "Vecina del otro lado del Kíndet. La casa la compraría el hermano para rentarla",
        "name": "Korina",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "telephon": "6141882916",
        "createdAt": 1698966684204,
        "lastname": "Rodríguez Villanueva",
        "id": "aWsiCOX2z7JPNW2i2ziN"
    },
    {
        "propCont": "Residencial Universidad EsoSe",
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "name": "Nallely",
        "telephon": "6143775569",
        "createdAt": 1696372433233,
        "email": "naalleely_flakis@hotmail.com",
        "selecMC": "Propiedades.com",
        "id": "b6ubCXdQa5W1UQ4gukBF"
    },
    {
        "rangeProp": "SGN",
        "createdAt": 1693616698590,
        "lastname": "García ",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "id": "bICHkGYxoaHmpJiLJw6w",
        "propCont": "Residencial Universidad Rli",
        "selecMC": "Lona en Propiedad",
        "name": "Rogelio",
        "telephon": "6142131074",
        "selecTP": "Casa"
    },
    {
        "createdAt": 1718126880010,
        "comContact": "Contactó por Albaterra Mch",
        "telephon": "8711571501",
        "selecMC": "Lamudi",
        "contactStage": "Etapa 1",
        "name": "carmen",
        "rangeProp": "TRC",
        "lastname": "sanchez",
        "typeContact": "Comprador",
        "id": "bkrlUBOhZdjHxxgK7mHS"
    },
    {
        "lastname": "De La Paz",
        "telephon": "6144278793",
        "name": "Gabriela ",
        "contactStage": "Etapa 1",
        "createdAt": 1698360141073,
        "rangeProp": "SGN",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "propCont": "Residencial Universidad Rli",
        "id": "bvThRtGxXluuyrMuHTr2"
    },
    {
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "selecMC": "Otro",
        "name": "Pauli",
        "telephon": "5583041066",
        "lastname": "prieto",
        "createdAt": 1709748532882,
        "email": "Global.moon21@gmail.com",
        "id": "ckQCxHfTQ7w4q51hET7Y"
    },
    {
        "contactStage": "Etapa 1",
        "email": "e4salgado@hotmail.com",
        "selecMC": "Lona en Propiedad",
        "selecTP": "Casa",
        "lastname": "Salgado",
        "typeContact": "Comprador",
        "telephon": "6142245038",
        "rangeProp": "QNT",
        "name": "Edith",
        "propCont": "Bosques de San Francisco I y II",
        "createdAt": 1689618507281,
        "id": "dAAkv6wBGhTBNRWVK8fe"
    },
    {
        "typeContact": "Comprador",
        "telephon": "6141964301",
        "lastname": "esperón",
        "contactStage": "Etapa 1",
        "comContact": "Es constructor y tiene cliente ",
        "rangeProp": "TRC",
        "selecMC": "",
        "name": "Alejandro",
        "createdAt": 1716334088091,
        "id": "dNQZryN5y2k74M99QuXI"
    },
    {
        "propCont": "San Felipe Vto",
        "lastname": "Guerrero",
        "selecMC": "Lona en Propiedad",
        "telephon": "6142297587",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "name": "Brendy",
        "createdAt": 1693597129558,
        "rangeProp": "TRC",
        "id": "e9GRCDmUgYD6HnidNyaF"
    },
    {
        "selecMC": "Lamudi",
        "telephon": "6143448381",
        "contactStage": "Etapa 1",
        "createdAt": 1706569229110,
        "name": "Álvaro",
        "lastname": "trevizo",
        "typeContact": "Comprador",
        "id": "eHLpSM5HoIu0JDtu60H1"
    },
    {
        "name": "Silvia",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "rangeProp": "CRT",
        "propCont": "San Felipe Jve",
        "lastname": "Carrillo",
        "typeContact": "Comprador",
        "createdAt": 1689867581493,
        "telephon": "6141007080",
        "selecTP": "Casa",
        "comContact": "La casa es para oficinas de un bufete de abogados, les urge comprar",
        "id": "eL6fMIHzvLTUnBpS0AHw"
    },
    {
        "lastname": "Marquez",
        "selecMC": "Propiedades.com",
        "name": "Adriana",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "email": "adry.emireth.marquez@gmail.com",
        "rangeProp": "TRC",
        "telephon": "6144563030",
        "contactStage": "Etapa 1",
        "createdAt": 1701110437903,
        "propCont": "Monteverde Mch",
        "id": "eLaf458qnRrXPvCD9eGt"
    },
    {
        "propCont": "Centro Jer",
        "lastname": "Gómez",
        "telephon": "6142555418",
        "typeContact": "Comprador",
        "selecTP": "Edificio",
        "createdAt": 1700000407804,
        "comContact": "Ya había contactado un par de veces",
        "contactStage": "Etapa 1",
        "rangeProp": "CRT",
        "email": " rsb@hotmail.com",
        "name": "Raúl",
        "selecMC": "Propiedades.com",
        "id": "eMj50ZAfK0WpeqnrsDl1"
    },
    {
        "typeContact": "Comprador",
        "lastname": "García",
        "comContact": "Quiere dos terrenos juntos",
        "propCont": "Labor de Terrazas Fac",
        "selecTP": "Terreno",
        "rangeProp": "PRM",
        "telephon": "6141474467",
        "contactStage": "Etapa 1",
        "createdAt": 1703630215413,
        "name": "Yarely",
        "selecMC": "",
        "id": "epu1h75g84CJbLM9fUDp"
    },
    {
        "rangeProp": "TRC",
        "selecTP": "Casa",
        "selecMC": "Lona en Propiedad",
        "name": "Juan Carlos",
        "lastname": "Guzmán",
        "createdAt": 1695340956635,
        "propCont": "San Felipe Vto",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "telephon": "6145399834",
        "id": "fcmQwALu2rdv2TWxpaU8"
    },
    {
        "email": "albertorojano@hotmail.com",
        "contactStage": "Etapa 1",
        "name": "Jorge",
        "propCont": "Parque Industrial Impulso VII y VIII",
        "rangeProp": "PRM",
        "telephon": "6144860975",
        "selecMC": "Lamudi",
        "comContact": "Van a abrir sucursal aquí en Chihuahua, de estructuras metálicas, ya tienen sucursles en Cancún y en Guadalajara.",
        "selecTP": "Terreno",
        "createdAt": 1694026585225,
        "lastname": "Rojano",
        "id": "glXaEG5lCi2agPyBGk0d",
        "typeContact": "Comprador"
    },
    {
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "telephon": "6271177019",
        "lastname": "soto garcía",
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "createdAt": 1709253605626,
        "name": "antony",
        "id": "gpADNZxMtEdvT9E8wiZK"
    },
    {
        "name": "alberto",
        "createdAt": 1713805654639,
        "telephon": "6141107845",
        "comContact": "Contactó por Google",
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "selecMC": "Referido",
        "lastname": "fernandez",
        "email": "bepo13021977@gmail.com",
        "id": "h1yxk7fMrpvMc0Qjavu3"
    },
    {
        "selecTP": "Terreno",
        "name": "Luisa",
        "rangeProp": "SXT",
        "selecMC": "Lona en Propiedad",
        "propCont": "Angel Trias Rpo",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "telephon": "6142394868",
        "createdAt": 1690315864558,
        "lastname": "Caballero ",
        "id": "hT4g9hkiyhKiwwEY1Ivg"
    },
    {
        "locaProperty": [
            "Noroeste",
            "Oeste"
        ],
        "selecTP": "Casa",
        "halfBathroom": "",
        "tagsProperty": [
            "Fracc._Privado",
            "Una_Planta"
        ],
        "lastname": "trillo",
        "rangeProp": "TRC",
        "createdAt": 1715797943114,
        "numBeds": 3,
        "budget": "5000000",
        "modePay": "",
        "numBaths": 2,
        "id": "huyze5lbd4qG1WqDSNjm",
        "typeContact": "Comprador",
        "telephon": "6142160784",
        "comContact": "Zona abierta pero no por las canteras",
        "contactStage": "Etapa 1",
        "email": "emma_trillo@yahoo.com.mx",
        "selecMC": "Lamudi",
        "numParks": 2,
        "name": "Emma"
    },
    {
        "createdAt": 1695685378634,
        "typeContact": "Comprador",
        "telephon": "6865690687",
        "propCont": "Quintas del Sol Ple",
        "rangeProp": "TRC",
        "lastname": "Grijalva",
        "contactStage": "Etapa 1",
        "selecMC": "Propiedades.com",
        "selecTP": "Casa",
        "name": "Carlos",
        "id": "iH658l1di0z1yQFnWcsN"
    },
    {
        "selecMC": "Lona en Propiedad",
        "propCont": "Marmol Rfe",
        "rangeProp": "PRM",
        "contactStage": "Etapa 1",
        "lastname": "Ramirez ",
        "selecTP": "Casa",
        "typeContact": "Comprador",
        "name": "Mayra",
        "telephon": "6144474901",
        "createdAt": 1689383311893,
        "id": "iQFM7EcmC1ryUSJAj45v"
    },
    {
        "contactStage": "Etapa 1",
        "telephon": "6141693284",
        "createdAt": 1720998537509,
        "selecMC": "Lona en Propiedad",
        "id": "ibjOhGHuVMcniDM69z9k",
        "typeContact": "Comprador",
        "lastname": "lazaro",
        "rangeProp": "SGN",
        "name": "almendra"
    },
    {
        "id": "imRiwlKqSRLBIuBBfSjk",
        "telephon": "6142461664",
        "createdAt": 1689711630410,
        "contactStage": "Etapa 1",
        "rangeProp": "TRC",
        "typeContact": "Inversionista",
        "name": "Isaac",
        "selecMC": "Lona en Propiedad",
        "propCont": "San Felipe Vto",
        "lastname": "Chavez",
        "selecTP": "Casa",
        "comContact": "Es el inversionista que habló con Julio, que está interesado en la casa de Jorge Velez"
    },
    {
        "typeContact": "Comprador",
        "name": "Yolanda",
        "comContact": "La casa es para la hija",
        "rangeProp": "TRC",
        "lastname": "gaytán",
        "telephon": "6145092437",
        "id": "kyXInwEJ0gX92CuNznDB",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "createdAt": 1709654761632
    },
    {
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "name": "María Teresa",
        "selecMC": "Propiedades.com",
        "createdAt": 1700000936690,
        "telephon": "6361174363",
        "rangeProp": "SGN",
        "lastname": "Enriquez Velázquez",
        "selecTP": "Casa",
        "email": "mtev240569ed@gmail.com",
        "propCont": "Bosques de San Pedro",
        "id": "lF75Z1jfluHyhVq3OUzv"
    },
    {
        "typeContact": "Comprador",
        "name": "Daniel",
        "telephon": "6141979732",
        "email": "bufd@hotmail.com",
        "lastname": "Bustos",
        "createdAt": 1706205832410,
        "selecMC": "Lamudi",
        "contactStage": "Etapa 1",
        "id": "lWYY2lFje0FzoQM950Fb"
    },
    {
        "contactStage": "Etapa 1",
        "telephon": "6141422831",
        "lastname": "Tarango",
        "selecMC": "Lona en Propiedad",
        "propCont": "Residencial Universidad EsoSe",
        "selecTP": "Casa",
        "typeContact": "Comprador",
        "createdAt": 1689700122444,
        "name": "Juan",
        "rangeProp": "TRC",
        "id": "ls5l66kLxDJeoFNgH8HP"
    },
    {
        "rangeProp": "TRC",
        "contactStage": "Etapa 1",
        "propCont": "San Felipe Vto",
        "name": "Mayra",
        "createdAt": 1694735123788,
        "selecTP": "Casa",
        "telephon": "6144884936",
        "typeContact": "Comprador",
        "lastname": "Domínguez",
        "selecMC": "Lona en Propiedad",
        "id": "nkrCBJEJzra15mUv4MKp"
    },
    {
        "comContact": "Contactó por Ángel Triss Rpo",
        "selecMC": "Lona en Propiedad",
        "lastname": "Gómez ",
        "createdAt": 1705788237250,
        "propCont": "Panamericana Rga",
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "rangeProp": "CRT",
        "telephon": "6142241650",
        "id": "oqjuHEIbyWIPFHXpKdKX",
        "name": "Andrés",
        "typeContact": "Comprador"
    },
    {
        "name": "Omar",
        "rangeProp": "TRC",
        "lastname": "Muñoz",
        "telephon": "6145049765",
        "comContact": "Para oficinas",
        "selecTP": "Casa",
        "propCont": "San Felipe Vto",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "typeContact": "",
        "createdAt": 1692917002091,
        "id": "pYFTHd3dtXsK7USXHjmc"
    },
    {
        "createdAt": 1689266381757,
        "numParks": "",
        "numBeds": "",
        "typeContact": "Comprador",
        "numBaths": "",
        "contactStage": "Etapa 1",
        "selecMC": "Lona en Propiedad",
        "modePay": "",
        "lastname": "Charrasqueado",
        "selecTP": "Casa",
        "propCont": "Pedregal de San Ángel",
        "telephon": "6142752415",
        "halfBathroom": "",
        "tagsProperty": [],
        "rangeProp": "CRT",
        "name": "Juan",
        "locaProperty": [],
        "id": "qTiejEa1DV6W8krU1UPg"
    },
    {
        "numBeds": "",
        "halfBathroom": "",
        "numParks": "",
        "id": "r0f0ZtP7dwQXTwifWPPo",
        "tagsProperty": [],
        "lastname": "chavira",
        "locaProperty": [
            "Noroeste",
            "Centronorte"
        ],
        "selecTP": "",
        "rangeProp": "",
        "budget": "2600000",
        "numBaths": "",
        "comContact": "Busca casa para el hijo con crédito de la esposa",
        "typeContact": "Comprador",
        "modePay": "",
        "selecMC": "Otro",
        "contactStage": "Etapa 1",
        "createdAt": 1721145651738,
        "telephon": "6142394685",
        "name": "sixto"
    },
    {
        "selecMC": "Referido",
        "lastname": "muñoz",
        "createdAt": 1720022297413,
        "comContact": "Busca terreno, casa o local comercial",
        "contactStage": "Etapa 1",
        "name": "rigoberto",
        "typeContact": "Comprador",
        "telephon": "6141526443",
        "id": "rS5x6B3QgSN8EytdLGkh"
    },
    {
        "selecTP": "Casa",
        "typeContact": "Comprador",
        "email": "https://www.matchhome.net/property/casa-en-venta-en-hacienda-regina-de-un-nivel-frente-a-parque?agent=enrique329",
        "contactStage": "Etapa 1",
        "selecMC": "Lamudi",
        "propCont": "Hacienda Regina Mch",
        "createdAt": 1698340775986,
        "name": "Ydira",
        "telephon": "6255943479",
        "rangeProp": "TRC",
        "id": "rgtBwucR0aHASwsg90D8"
    },
    {
        "createdAt": 1690929925895,
        "telephon": "6143445631",
        "comContact": "Está vendiendo su casa en Residencial Universidad",
        "selecMC": "Lona en Propiedad",
        "id": "ruINPXRc3HwVKSA812MI",
        "name": "Rigoberto",
        "lastname": "Ortega",
        "propCont": "San Felipe Vto",
        "contactStage": "Etapa 1",
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "selecTP": "Casa"
    },
    {
        "rangeProp": "QNT",
        "selecTP": "Terreno",
        "selecMC": "Propiedades.com",
        "name": "Esmeralda",
        "contactStage": "Etapa 1",
        "createdAt": 1697215580300,
        "telephon": "6142509010",
        "propCont": "Villa Juarez Jma",
        "typeContact": "Comprador",
        "lastname": "Turcott",
        "id": "rukTmWFM5s8NHAh3jRx4"
    },
    {
        "typeContact": "",
        "selecTP": "Casa",
        "selecMC": "",
        "propCont": "Villa Rca",
        "contactStage": "Etapa 1",
        "createdAt": 1705511773688,
        "name": "Socorro",
        "lastname": "Sanchez",
        "comContact": "Va a llevar a la patrona para que vea la ubicación",
        "telephon": "6142660410",
        "rangeProp": "SGN",
        "id": "t9Y381Ivp7F2BkJwByUt"
    },
    {
        "comContact": "Ya lo tenía dado de alta, creo que le estábamos vendiendo una casa.",
        "name": "Noel",
        "selecTP": "Local Comercial",
        "typeContact": "Comprador",
        "lastname": "Beltran",
        "rangeProp": "SGN",
        "propCont": "Quintas Carolinas Mch",
        "selecMC": "Propiedades.com",
        "telephon": "6141614430",
        "email": "NBELTRAN23@HOTMAIL.COM",
        "contactStage": "Etapa 1",
        "createdAt": 1696093459618,
        "id": "trUyhY4WN6YPTXnUGavk"
    },
    {
        "propCont": "San Felipe Vto",
        "selecMC": "Lona en Propiedad",
        "contactStage": "Etapa 1",
        "selecTP": "Casa",
        "rangeProp": "TRC",
        "createdAt": 1692130608759,
        "typeContact": "Comprador",
        "name": "Cinthia",
        "lastname": "Vargas",
        "telephon": "6142848029",
        "id": "uAfWbu6BzHE52He7gyYB"
    },
    {
        "rangeProp": "TRC",
        "selecMC": "Propiedades.com",
        "name": "Silvia",
        "propCont": "San Felipe Vto",
        "typeContact": "Comprador",
        "selecTP": "Casa",
        "lastname": "Sánchez ",
        "createdAt": 1696711883519,
        "comContact": "Inversionista ",
        "contactStage": "Etapa 1",
        "id": "ug2RUr3thxjEYkv1O34V"
    },
    {
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "lastname": "Jaulet Caballero ",
        "rangeProp": "CRT",
        "name": "Luis Carlos",
        "propCont": "San Felipe Jve",
        "telephon": "6142457355",
        "selecMC": "Lona en Propiedad",
        "createdAt": 1692310464815,
        "typeContact": "Comprador",
        "id": "vAWF8InKnR3EeTTyDx6y"
    },
    {
        "telephon": "6144067288",
        "comContact": "Contactó por San Felipe Vto. Para construir departamentos. ",
        "contactStage": "Etapa 1",
        "createdAt": 1695664786406,
        "typeContact": "Comprador",
        "rangeProp": "TRC",
        "selecTP": "Terreno",
        "name": "Oscar",
        "selecMC": "Lona en Propiedad",
        "lastname": "Toledo",
        "propCont": "Quintas del Sol Rli",
        "id": "vD7iuFLkOQ6naZWIfmbm"
    },
    {
        "contactStage": "Etapa 1",
        "telephon": "6143642011",
        "createdAt": 1688238254380,
        "lastname": "López ",
        "selecMC": "Lona en Propiedad",
        "selecTP": "Terreno",
        "rangeProp": "TRC",
        "name": "Virgilo",
        "propCont": "Quintas del Sol Rli",
        "typeContact": "Comprador",
        "id": "wXlSyNJUHchGEpMGI5oZ"
    },
    {
        "rangeProp": "TRC",
        "contactStage": "Etapa 1",
        "createdAt": 1699734819221,
        "name": "Dra",
        "propCont": "San Felipe Vto",
        "typeContact": "Comprador",
        "telephon": "6143553033",
        "selecTP": "Casa",
        "lastname": "Flores",
        "selecMC": "Lona en Propiedad",
        "id": "xkyOnlpMyDbkdQQeUTEr"
    },
    {
        "createdAt": 1713375549276,
        "contactStage": "Etapa 1",
        "rangeProp": "TRC",
        "typeContact": "Comprador",
        "selecMC": "Lamudi",
        "email": "adrianferb@hotmail.com",
        "lastname": "Espinoza Palomino",
        "telephon": "6143749240",
        "name": "Mario Adrián",
        "id": "y1GbHFKuaLWlvRIy4lve"
    },
    {
        "createdAt": 1706634591518,
        "telephon": "6144586840",
        "selecMC": "Lamudi",
        "name": "monica",
        "lastname": "chávez",
        "typeContact": "Comprador",
        "contactStage": "Etapa 1",
        "id": "y3dMZmZbxaTVR3ALmnZM"
    },
    {
        "name": "Antonia",
        "selecTP": "Casa",
        "contactStage": "Etapa 1",
        "createdAt": 1708205118242,
        "selecMC": "Lona en Propiedad",
        "lastname": "Zubias",
        "typeContact": "",
        "telephon": "614 313 5366",
        "propCont": "Villa Rca",
        "rangeProp": "SGN",
        "id": "yMGIt4qDDMgCQNsUqNhN"
    },
    {
        "telephon": "6141214929",
        "selecMC": "",
        "comContact": "La casa es para el hermano",
        "name": "esther",
        "lastname": "torres",
        "contactStage": "Etapa 1",
        "rangeProp": "",
        "typeContact": "Comprador",
        "createdAt": 1708556002760,
        "id": "yhJcfDQKx00IRglePUy5"
    }
  ],
    "properties":
    [
        {
        "description": "Descripción Excelente Terreno Comercial . ( Jardín Corona ) , Ave. Teofilo Borunda y Ave. Cristobal Colón.  T 8930. m2 C 640 m2  $ 71,434,000 Características Exterior Jardín Patio General Permitido fumar",
        "titulo": "TTTTerreno en Venta Excelente Punto (Jardín Corona), en el centro.",
        "colonia": "Zona Centro",
        "price": 71434000,
        "operacion": "Venta",
        "claveEB": "EB-EA6990",
        "urlImage": "https://assets.easybroker.com/property_images/1316990/19639310/EB-EA6990.jpeg?version=1572553188",
        "urlProp": "https://www.matchhome.net/property/terreno-en-venta-excelente-punto-jardin-corona",
        "urlSinergy": "https://www.matchhome.net/property/terreno-en-venta-excelente-punto-jardin-corona",
        "nameProperty": "Zona Centro00000",
        "tagsProperty": [],
        "locaProperty": ["CentroSur"],
        "selectTP": "Terreno comercial",
        "areaTotal": 8
        },
        {
        "description": "Descripción Excelente inversión, ubicado en el primer cuadro de la ciudad, a unos pasos de la parada de autobuses, consta de tres níveles.  Tiene espacios para varias oficinas y para almacén.  Comienza a recibir ganancias al instante, ya que está rentado actualmente por más de 6 años. Características Exterior Cisterna Facilidad para estacionarse General Bodega Cuarto de servicio Recreación Salón de usos múltiples",
        "titulo": "Edificio en Venta en el Centro de la Ciudad.",
        "colonia": "Zona Centro",
        "price": 7250000,
        "operacion": "Venta",
        "claveEB": "EB-MT6864",
        "urlImage": "https://assets.easybroker.com/property_images/3586864/58393033/EB-MT6864.jpg?version=1677691642",
        "urlProp": "https://www.matchhome.net/property/edificio-en-venta-en-el-centro-de-la-ciudad-zona-centro",
        "urlSinergy": "https://www.matchhome.net/property/edificio-en-venta-en-el-centro-de-la-ciudad-zona-centro",
        "nameProperty": "Zona Centro",
        "tagsProperty": [],
        "locaProperty": ["CentroSur"],
        "selectTP": "Edificio",
        "park": 3,
        "areaBuilding": 143,
        "areaTotal": 143,
        "flors": 3
        },
        {
        "description": "Descripción Ubicada en fraccionamiento privado, cerca de los principales hoteles, restaurantes y centros comerciales, con vigilancia las 24hrs.  PLANTA BAJA Contiene sala - comedor, cocina, lavandería, recámara principal con baño y vestidor, 1/2 baño, cochera techada para 2 autos, pasillo de servicio, patio y jardín al frente.  PLANTA ALTA 2 recámaras con baño y vestidor propio, y estancia con balcón.  EQUIPAMIENTO  Cocina integral, paneles solares, mini splits en cada área, pisos con calefacción radiante, techo con aislante, muros de tabique con aislante, ventanería con doble vidrio, hidroneumático, boiler, tanque estacionario, carpintería de encino y granito, riego automatizado, persianas y candiles.  T 301 m2 C 282 m2 Características Exterior Balcón Cisterna Estacionamiento techado Facilidad para estacionarse Jardín Patio Riego por aspersión General Aire acondicionado Calefacción Cocina Cocina integral Dos plantas Fraccionamiento privado Hidroneumático Mascotas permitidas Permitido fumar Seguridad 24 horas",
        "titulo": "Casa en Venta en Pedregal del Alba, con Recámara en Planta Baja..",
        "colonia": "Pedregal del Alba Residencial",
        "price": 7200000,
        "operacion": "Venta",
        "claveEB": "EB-NG6824",
        "urlImage": "https://assets.easybroker.com/property_images/3716824/60782340/EB-NG6824.jpg?version=1683074779",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-pedregal-del-alba-con-recamara-en-planta-baja-pedregal-del-alba-residencial",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-pedregal-del-alba-con-recamara-en-planta-baja-pedregal-del-alba-residencial",
        "nameProperty": "Pedregal del Alba Residencial",
        "tagsProperty": ["Fracc. Privado", "Recamamara en PB"],
        "locaProperty": [],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 3,
        "halfBathroom": 1,
        "park": 2,
        "areaBuilding": 282,
        "areaTotal": 301,
        "flors": 2
        },
        {
        "description": "Descripción Ubicada a 5 min. del centro de la ciudad, por la avenida Cuauhtémoc, casa muy amplia.  Tiene 3 recámaras muy amplias, con closet cada una, estancia, sala, comedor, cocina integral con alacena. Cochera techada. Tiene un departamento con baño, puede usarse como oficina, o área de juegos. Amplio patio con árboles frutales.  EQUIPAMIENTO Aire acondicionado, calefacción y tanque estacionario. Características Exterior Cisterna Estacionamiento techado Facilidad para estacionarse Jardín Patio General Aire acondicionado Calefacción Cocina Cocina integral Dos plantas Estudio Hidroneumático Mascotas permitidas Recreación Salón de usos múltiples",
        "titulo": "Casa en Venta en Santa Rita.",
        "colonia": "Santa Rita",
        "price": 3500000,
        "operacion": "Venta",
        "claveEB": "EB-NI6733",
        "urlImage": "https://assets.easybroker.com/property_images/3736733/61150309/EB-NI6733.jpg?version=1683830823",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-santa-rita-f8d16cf6-3717-4fbb-9dc9-943d356dd1b6",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-santa-rita-f8d16cf6-3717-4fbb-9dc9-943d356dd1b6",
        "nameProperty": "Santa Rita",
        "tagsProperty": ["Patio Amplio"],
        "locaProperty": ["CentroSur"],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 2,
        "park": 2,
        "areaBuilding": 179,
        "areaTotal": 345,
        "flors": 2
        },
        {
        "description": "Descripción A pocos minutos del parque industrial norte, uach pantel 2 y tiendas de conveniencia.  La casa consta de 2 níveles.  PLANTA BAJA Sala - comedor, 1/2 baño y patio.  PLANTA ALTA Estancia, 3 recámaras ( la principal con baño y closet - vestidor), 2 baños compartidos, cuarto de lavandería  EQUIPAMIENTO Aire lavado master cool, boiler, lamparas y candiles. Persianas, puerta principal de seguridad, cocina con granito, poliuretano espriado en azotea. Características Exterior Balcón Cisterna Estacionamiento techado Facilidad para estacionarse Patio General Aire acondicionado Cocina Cocina integral Dos plantas Fraccionamiento privado Hidroneumático Seguridad 24 horas",
        "titulo": "Casa en Venta en Aldabas, al Norte de la Ciudad.",
        "colonia": "Las Aldabas I a La IX",
        "price": 2600000,
        "operacion": "Venta",
        "claveEB": "EB-LY6990",
        "urlImage": "https://assets.easybroker.com/property_images/3376990/54561918/EB-LY6990.jpg?version=1668193307",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-aldabas-al-norte-de-la-ciudad",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-aldabas-al-norte-de-la-ciudad",
        "nameProperty": "Las Aldabas I a La IX",
        "tagsProperty": ["Fracc. Privado"],
        "locaProperty": ["Norte"],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 2,
        "halfBathroom": 1,
        "park": 1,
        "areaBuilding": 193,
        "areaTotal": 126,
        "flors": 2
        },
        {
        "description": "Descripción Departamento de lujo, de los más exclusivos de la ciudad, con las mejores vistas y mayor plusvalía.  Es de 2 recámaras, 2 baños, cocina, lavandería, chimenea, oficina, sala/ comedor, estancia y balcón.  EQUIPAMIENTO Unidad de paquete frío/ calor, 2 boilers, persianas eléctricas, cámaras de seguridad, sonido ambiental con bocinas Bose, 3 cajones de estacionamiento y bodega para almacenamiento.  AMENIDADES DE LA TORRE Lobby, gimnasio, alberca exterior e interior, sala de juntas, salón para eventos, jacuzzi, zona de asador, área social, área para niños y seguridad 24 hrs.  C 188 m2 Mantenimiento $ 5,800. Características Exterior Balcón Cisterna Estacionamiento techado Facilidad para estacionarse Roof garden Terraza General Accesibilidad para adultos mayores Accesibilidad para personas con discapacidad Aire acondicionado Bodega Calefacción Chimenea Cocina Elevador Hidroneumático Seguridad 24 horas Recreación Alberca Área de juegos infantiles Gimnasio Jacuzzi Salón de usos múltiples",
        "titulo": "Departamento en Venta en Torre Lúmina",
        "colonia": "Barrancas",
        "price": 11000000,
        "operacion": "Venta",
        "claveEB": "EB-NS4769",
        "urlImage": "https://assets.easybroker.com/property_images/3834769/62956596/EB-NS4769.jpg?version=1687545680",
        "urlProp": "https://www.matchhome.net/property/departamento-en-venta-en-torre-lumina-barrancas",
        "urlSinergy": "https://www.matchhome.net/property/departamento-en-venta-en-torre-lumina-barrancas",
        "nameProperty": "Barrancas",
        "tagsProperty": [],
        "locaProperty": ["NorOeste"],
        "selectTP": "Departamento",
        "beds": 2,
        "bathroom": 2,
        "park": 3,
        "areaBuilding": 188
        },
        {
        "description": "Descripción Fraccionamiento privado, ubicado en una de las zonas con mucha plusvalía, es encuentra cerca de los pricipales centros comerciales de la ciudad.  PLANTA BAJA Se encuentra sala - comedor, cocina con granito, lavandería, 1/2 baño, cochera para 2 autos, patio con jacuzzi y asador.  PLANTA ALTA Estancia, recámara principal con baño y vestidor, jacuzzi y terraza, dos recámaras secundarias, cada una con terraza y closet, baño completo compartido, bodega.  EQUIPAMIENTO 2 calefacciones, 2 aires acondicionado, hidroneumático, cisterna 5000 lts. boiler, paneles solares, gas natutal, ventanería de doble vidrio, refrigerador, horno, lavadora, secadora, 7 televisiones, portón eléctrico, circuito cerrado, carpintería de encino sólido, cerámica en patio y cochera..  T 189 m2 C 320 m2 Características Exterior Cisterna Estacionamiento techado Facilidad para estacionarse Jardín Parrilla Patio Terraza General Aire acondicionado Bodega Calefacción Circuito cerrado Cocina equipada Dos plantas Fraccionamiento privado Hidroneumático Mascotas permitidas Panel solar Permitido fumar Seguridad 24 horas Recreación Jacuzzi",
        "titulo": "Casa en venta en Residencial Valdivia. Completamente Equipada.",
        "colonia": "Valdivia Residencial",
        "price": 5400000,
        "operacion": "Venta",
        "claveEB": "EB-NR8145",
        "urlImage": "https://assets.easybroker.com/property_images/3828145/62830693/EB-NR8145.jpg?version=1687309341",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-residencial-valdivia-completamente-equipada",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-residencial-valdivia-completamente-equipada",
        "nameProperty": "Valdivia Residencial",
        "tagsProperty": ["Fracc. Privado", "Recamamara en PB"],
        "locaProperty": [],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 2,
        "halfBathroom": 1,
        "park": 2,
        "areaBuilding": 320,
        "areaTotal": 189,
        "flors": 2
        },
        {
        "description": "Descripción Céntrica casa ubicada muy cerca de la Ave. Américas y de la Ave. Vallarta.  Es de un nivel, consta de: Sala/ comedor, cocina, 3 recámaras, 1 baño, patio con construcción, para departamento en obra negra, y cochera para 2 autos.  EQUIPAMIENTO Aire acondicionado, gas natural, rejas y barandales.  C 160 m2 T 300 m2. Características Exterior Facilidad para estacionarse Jardín Patio General Aire acondicionado Cocina Mascotas permitidas Permitido fumar Una sola planta",
        "titulo": "Casa en Venta en Las Granjas, de un Piso",
        "colonia": "Las Granjas",
        "price": 2750000,
        "operacion": "Venta",
        "claveEB": "EB-NR6344",
        "urlImage": "https://assets.easybroker.com/property_images/3826344/62797066/EB-NR6344.jpg?version=1687281114",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-las-granjas-de-un-piso",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-las-granjas-de-un-piso",
        "nameProperty": "Las Granjas",
        "tagsProperty": ["Una Planta"],
        "locaProperty": ["NorOeste"],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 1,
        "park": 2,
        "areaBuilding": 160,
        "areaTotal": 300,
        "flors": 1
        },
        {
        "description": "Descripción Propiedad en esquina, con uso de suelo comercial, muy céntrico. Consta de oficinas, área para atención a clientes, almacenes cocheras, etc.  EQUIPAMIENTO  Sub estación de 75 kvas Cisterna con hidro neumático Cochera eléctrica.  T 917 m2 C 802 m2 Características Exterior Cisterna Estacionamiento techado Facilidad para estacionarse Patio General Aire acondicionado Bodega Una sola planta Mascotas permitidas Permitido fumar",
        "titulo": "Atención Inversionistas, amplio terreno en la Obrera, ideal para oficinas.",
        "colonia": "Obrera",
        "price": 6300000,
        "operacion": "Venta",
        "claveEB": "EB-KM1860",
        "urlImage": "https://assets.easybroker.com/property_images/2991860/47645226/EB-KM1860.jpg?version=1653420469",
        "urlProp": "https://www.matchhome.net/property/atencion-inversionistas-amplio-terreno-en-la-obrera-ideal-para-oficinas",
        "urlSinergy": "https://www.matchhome.net/property/atencion-inversionistas-amplio-terreno-en-la-obrera-ideal-para-oficinas",
        "nameProperty": "Obrera",
        "tagsProperty": [],
        "locaProperty": ["CentroSur"],
        "selectTP": "Terreno",
        "areaTotal": 917
        },
        {
        "description": "Descripción Ubicada cerca de la presa el rejón, en fracconamiento privado, con fácil acceso por la Ave. Teófilo Borunda.  La casa consta de: Cocina, sala, comedor, lavandería, 2 recámaras, la prinipal con baño y vestidor. Un baño completo y patio.  EQUIPAMIENTO Cocina con cubierta de granito, campana, boiler, cisterna, 2800 litros, hidroneumático, closets, canceles de baño, aire y calefacción.  T 151 m2 C 114 m2 Características Exterior Cisterna Estacionamiento techado Facilidad para estacionarse Patio General Aire acondicionado Calefacción Cocina Cocina integral Fraccionamiento privado Hidroneumático Mascotas permitidas Seguridad 24 horas Una sola planta",
        "titulo": "Casa en Venta en Hacienda Regina, De un Nível, Frente a Parque",
        "colonia": "Hacienda Carlota",
        "price": 2590000,
        "operacion": "Venta",
        "claveEB": "EB-NQ0447",
        "urlImage": "https://assets.easybroker.com/property_images/3810447/62484242/EB-NQ0447.jpg?version=1686677597",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-hacienda-regina-de-un-nivel-frente-a-parque",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-en-hacienda-regina-de-un-nivel-frente-a-parque",
        "nameProperty": "Hacienda Carlota",
        "tagsProperty": ["Fracc. Privado", "Frente Parque"],
        "locaProperty": ["Oeste"],
        "selectTP": "Casa",
        "beds": 2,
        "bathroom": 2,
        "park": 1,
        "areaBuilding": 114,
        "areaTotal": 151,
        "flors": 1
        },
        {
        "description": "Descripción Plaza comercial ubicada muy cerca de la presa el rejón, cuenta con gran afluencia vehicular.  El local tiene una superficie de 96.44 m2. con un mexanine de 35 m2, tiene áreas comunes con una supérficie de 13.20 %. Se encuentra habiltado y equipado. Características Exterior Facilidad para estacionarse General Accesibilidad para adultos mayores Aire acondicionado Alarma Bodega",
        "titulo": "Local Comercial en Venta en Plaza Andares.",
        "colonia": "Labor de Terrazas",
        "price": 3300000,
        "operacion": "Venta",
        "claveEB": "EB-NO1759",
        "urlImage": "https://assets.easybroker.com/property_images/3791759/62174120/EB-NO1759.jpg?version=1686076532",
        "urlProp": "https://www.matchhome.net/property/local-comercial-en-venta-en-plaza-andares",
        "urlSinergy": "https://www.matchhome.net/property/local-comercial-en-venta-en-plaza-andares",
        "nameProperty": "Labor de Terrazas",
        "tagsProperty": [],
        "locaProperty": [],
        "selectTP": "Local comercial",
        "bathroom": 1,
        "areaBuilding": 96,
        "areaTotal": 96
        },
        {
        "description": "Descripción Cerca del periférico de la juventud, por el campus II de la uach. De 2 plantas.  PLANTA BAJA Sala, comedor, cocina, lavandería, patio amplio y cochera para 3 autos.  PLANTA ALTA Estancia, Recámara principal con vestidor y baño completo, las otras 2 recámaras secundarias con closets, 1 baño completo.  EQUIPAMIENTO  Campana, estufa, muebles en lavandería y estancia, ventiladores con iluminación en recámaras y estancia, asador, malla sombra en patio, barra y luces, tanque estacionario de 300 kg. aire acondicionado, calefacción, tinaco de 1000 lts., boiler de paso, y pequeña bomba de presión. Características Exterior Cisterna Estacionamiento techado Facilidad para estacionarse Parrilla Patio General Aire acondicionado Calefacción Cocina Cocina integral Dos plantas Hidroneumático Mascotas permitidas Permitido fumar Recreación Salón de usos múltiples",
        "titulo": "Casa en Venta al Norte en Cordilleras III",
        "colonia": "Cordilleras I, II y III",
        "price": 3100000,
        "operacion": "Venta",
        "claveEB": "EB-LL2596",
        "urlImage": "https://assets.easybroker.com/property_images/3242596/51987030/EB-LL2596.jpg?version=1662659932",
        "urlProp": "https://www.matchhome.net/property/casa-en-venta-al-norte-en-cordilleras-iii",
        "urlSinergy": "https://www.matchhome.net/property/casa-en-venta-al-norte-en-cordilleras-iii",
        "nameProperty": "Cordilleras I, II y III",
        "tagsProperty": ["Patio Amplio"],
        "locaProperty": [],
        "selectTP": "Casa",
        "beds": 3,
        "bathroom": 2,
        "park": 3,
        "areaBuilding": 207,
        "areaTotal": 179,
        "flors": 1
        },
        {
        "description": "Descripción Plaza ubicada cerca del parque reliz, con gran afluencia de clientes. También tiene áreas comunes.  El local tiene de superficie 70 m2, con un mezanine de 35 % para construcción, está completamente equipado y habilitado. Características Exterior Cisterna Facilidad para estacionarse General Accesibilidad para adultos mayores Aire acondicionado Bodega",
        "titulo": "Local en Venta en Plaza Travessía.",
        "colonia": "Labor de Terrazas",
        "price": 3500000,
        "operacion": "Venta",
        "claveEB": "EB-NN9233",
        "urlImage": "https://assets.easybroker.com/property_images/3789233/62125309/EB-NN9233.jpg?version=1685991463",
        "urlProp": "https://www.matchhome.net/property/local-en-venta-en-plaza-travessia",
        "urlSinergy": "https://www.matchhome.net/property/local-en-venta-en-plaza-travessia",
        "nameProperty": "Labor de Terrazas",
        "tagsProperty": [],
        "locaProperty": [],
        "selectTP": "Local comercial",
        "bathroom": 1,
        "areaBuilding": 70,
        "areaTotal": 70
        },
        {
        "description": "Descripción Local comercial ubicado cerca del parque metropolitano 3 presas, plaza comercial con gran afluencia de clientela y con acceso para discapacitados, sin problema de estacionamiento.  Superficie de 98.55 m2 Mezanine al 35 % Áreas comunes 32.94 %  Local habilitado y equipado.  Plaza Summa Características Exterior Facilidad para estacionarse General Accesibilidad para adultos mayores Accesibilidad para personas con discapacidad Aire acondicionado Alarma Bodega",
        "titulo": "En Venta Local Comercial, En Plaza Summa.",
        "colonia": "Labor de Terrazas",
        "price": 3700000,
        "operacion": "Venta",
        "claveEB": "EB-NN5334",
        "urlImage": "https://assets.easybroker.com/property_images/3785334/62050158/EB-NN5334.jpg?version=1685728011",
        "urlProp": "https://www.matchhome.net/property/en-venta-local-comercial-en-plaza-summa",
        "urlSinergy": "https://www.matchhome.net/property/en-venta-local-comercial-en-plaza-summa",
        "nameProperty": "Labor de Terrazas",
        "tagsProperty": [],
        "locaProperty": [],
        "selectTP": "Local comercial",
        "bathroom": 1,
        "park": 2,
        "areaBuilding": 98,
        "areaTotal": 98
        }
    ]
      

}